### ISSUE TITLE
Any license for this project ?

### ISSUE THREAD

**Issue by why-blip** [pllk/sqltrainer#1]
Hi
I forked this project to translate it to French. 
If it had an open source licence, I could ask to have it bundled to some training tools we offer to our students.

Great work btw!

**Comment by pllk** [comment]
Thanks! You can use the code using the license Creative Commons BY-NC-SA 4.0.

**Comment by why-blip** [comment]
Can you then insert the proper License.md file in your repo ?

**Comment by pllk** [comment]
Added to README.md, it seems GitHub doesn't provide a license template for that license and I don't want to use too much time for this.

**Comment by why-blip** [comment]
You can add a link to https://creativecommons.org/licenses/by-nc-sa/4.0/
I guess your phrase is sufficient. Thanks.
